FROM python:3.9-slim

RUN pip install --upgrade pip
RUN pip install kafka-python
RUN pip install cassandra-driver

WORKDIR /hw8/kafka-cassandra
COPY from_kafka.py .

ENTRYPOINT ["python", "from_kafka.py"]
